server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    post: 5672
    username:
    password:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/Spring Cloud MSA/e-commerce/native-file-repo
        git:
#          uri: file:///${user.home}\Desktop\Spring Cloud MSA\e-commerce\git-local-repo
          uri: https://github.com/K-MHoon/spring-cloud-config.git
#          username:
#          password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh